#!/usr/bin/with-contenv bash

# Install flexget last (it might force specific versions of other packages).
if [[ -z "${FLEXGET_VERSION}" ]]; then
  pip install -U -q flexget
else
  pip install -U -q flexget=="${FLEXGET_VERSION}"
fi
